# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# set_TBD.py
# Created on: 2014-04-29 16:51:47.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("C:/Users/SES/Projects/130401/700_gis/SES/SES.gdb/SES_Toolbox")


# Local variables:

# Process: set_TBD
arcpy.gp.toolbox = "C:/Users/SES/Projects/130401/700_gis/SES/SES.gdb/SES_Toolbox";
# Warning: the toolbox C:/Users/SES/Projects/130401/700_gis/SES/SES.gdb/SES_Toolbox DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.Model(...) with arcpy.Model_ALIAS(...)
arcpy.gp.Model()

