# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# tbd2.py
# Created on: 2014-04-29 16:59:11.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
SLAMM_landuse = "SLAMM_landuse"
SLAMM_landuse__3_ = "C:\\Users\\SES\\Projects\\130401\\700_gis\\SES\\SES.gdb\\wrk\\SLAMM_landuse"

# Process: Calculate Field
arcpy.CalculateField_management(SLAMM_landuse__3_, "WDOT_HWY", "\"TBD\"", "PYTHON_9.3", "")

